CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	email VARCHAR(40) NOT NULL,
	password VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	author VARCHAR(40) NOT NULL,
	pub_date DATE NOT NULL,
	synopsis VARCHAR(300) NOT NULL DEFAULT '',
	fk_possessor INT,
	FOREIGN KEY(fk_possessor)
		REFERENCES users(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
